cargo-features = []

[workspace]
resolver = "2"
members = ["cli", "lib", "cbits", "lib/gen-protos", "lib/testutils"]

[workspace.package]
version = "0.14.0"
license = "Apache-2.0"
rust-version = "1.71"                                 # NOTE: remember to update CI, contributing.md, changelog.md, and flake.nix
edition = "2021"
readme = "README.md"
homepage = "https://github.com/martinvonz/jj"
repository = "https://github.com/martinvonz/jj"
documentation = "https://martinvonz.github.io/jj/"
categories = ["version-control", "development-tools"]
keywords = ["VCS", "DVCS", "SCM", "Git", "Mercurial"]

[workspace.dependencies]
anyhow = "1.0.79"
assert_cmd = "2.0.8"
assert_matches = "1.5.0"
async-trait = "0.1.77"
backoff = "0.4.0"
blake2 = "0.10.6"
bytes = "1.5.0"
cc = "1.0"
cargo_metadata = "0.17.0"
clap = { version = "4.4.18", features = [
    "derive",
    "deprecated",
    "wrap_help",
    "string",
] }
clap_complete = "4.4.10"
clap-markdown = "0.1.3"
clap_mangen = "0.2.10"
chrono = { version = "0.4.33", default-features = false, features = [
    "std",
    "clock",
] }
config = { version = "0.13.4", default-features = false, features = ["toml"] }
criterion = "0.5.1"
crossterm = { version = "0.27", default-features = false }
digest = "0.10.7"
dirs = "5.0.1"
either = "1.9.0"
esl01-renderdag = "0.3.0"
futures = "0.3.30"
git2 = "0.18.2"
gix = { version = "0.56.0", default-features = false, features = [
    "index",
    "max-performance-safe",
] }
glob = "0.3.1"
hex = "0.4.3"
indexmap = "2.2.2"
insta = { version = "1.34.0", features = ["filters"] }
itertools = "0.11.0"
libc = { version = "0.2.153" }
maplit = "1.0.2"
num_cpus = "1.16.0"
once_cell = "1.19.0"
ouroboros = "0.18.0"
pest = "2.7.7"
pest_derive = "2.7.7"
pollster = "0.3.0"
pretty_assertions = "1.4.0"
prost = "0.11.9"
prost-build = "0.11.9"
rand = "0.8.5"
rand_chacha = "0.3.1"
rayon = "1.8.1"
ref-cast = "1.0.22"
regex = "1.10.3"
rpassword = "7.3.1"
rustix = { version = "0.38.31", features = ["fs"] }
scm-record = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.113"
slab = "0.4.9"
smallvec = { version = "1.13.0", features = [
    "const_generics",
    "const_new",
    "union",
] }
strsim = "0.10.0"
tempfile = "3.10.0"
test-case = "3.3.1"
textwrap = "0.16.0"
thiserror = "1.0.56"
timeago = { version = "0.4.2", default-features = false }
tokio = { version = "1.36.0" }
toml_edit = { version = "0.19.15", features = ["serde"] }
tracing = "0.1.40"
tracing-chrome = "0.7.1"
tracing-subscriber = { version = "0.3.18", default-features = false, features = [
    "std",
    "ansi",
    "env-filter",
    "fmt",
] }
unicode-width = "0.1.11"
version_check = "0.9.4"
watchman_client = { version = "0.8.0" }
whoami = "1.4.1"
zstd = "0.12.4"

# put all inter-workspace libraries, i.e. those that use 'path = ...' here in
# their own (alphabetically sorted) block

jj-cbits = { path = "cbits", version = "0.14.0" }
jj-lib = { path = "lib", version = "0.14.0" }
testutils = { path = "lib/testutils" }

[profile.release]
strip = "debuginfo"
codegen-units = 1
