[workspace]

[package]
name = "rust-third-party"
version = "0.0.0"
publish = false
edition = "2021"

# Dummy target to keep Cargo happy
[[bin]]
name = "fake"
path = "/dev/null"

[dependencies]
anyhow = "1.0.75"
assert_cmd = "2.0.8"
assert_matches = "1.5.0"
async-trait = "0.1.74"
backoff = "0.4.0"
blake2 = "0.10.6"
byteorder = "1.5.0"
bytes = "1.5.0"
cargo_metadata = "0.17.0"
clap = { version = "4.4.7", features = ["derive", "deprecated", "wrap_help"] }
clap_complete = "4.4.4"
clap_mangen = "0.2.10"
chrono = { version = "0.4.31", default-features = false, features = [
    "std",
    "clock",
] }
config = { version = "0.13.2", default-features = false, features = ["toml"] }
criterion = "0.5.1"
crossterm = { version = "0.26", default-features = false }
digest = "0.10.7"
dirs = "5.0.1"
either = "1.9.0"
esl01-renderdag = "0.3.0"
futures = "0.3.29"
glob = "0.3.1"
git2 = "0.17.2"
hex = "0.4.3"
itertools = "0.11.0"
indexmap = "2.0.2"
libc = { version = "0.2.149" }
insta = { version = "1.34.0", features = ["filters"] }
maplit = "1.0.2"
num_cpus = "1.16.0"
once_cell = "1.18.0"
pest = "2.7.5"
pest_derive = "2.7.5"
pretty_assertions = "1.4.0"
prost = "0.11.9"
prost-build = "0.11.9"
rand = "0.8.5"
rand_chacha = "0.3.1"
rayon = "1.8.0"
regex = "1.10.2"
rpassword = "7.2.0"
rustix = { version = "0.38.21", features = ["fs"] }
smallvec = { version = "1.11.1", features = [
    "const_generics",
    "const_new",
    "union",
] }
scm-record = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"
slab = "0.4.9"
strsim = "0.10.0"
tempfile = "3.8.1"
test-case = "3.2.1"
textwrap = "0.16.0"
thiserror = "1.0.50"
timeago = { version = "0.4.2", default-features = false }
toml_edit = { version = "0.19.15", features = ["serde"] }
tracing = "0.1.40"
tracing-chrome = "0.7.1"
tracing-subscriber = { version = "0.3.17", default-features = false, features = [
    "std",
    "ansi",
    "env-filter",
    "fmt",
] }
tokio = { version = "1.33.0" }
unicode-width = "0.1.11"
watchman_client = { version = "0.8.0" }
whoami = "1.4.1"
version_check = "0.9.4"
zstd = "0.12.4"
