name: Codespell

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
      - uses: codespell-project/actions-codespell@94259cd8be02ad2903ba34a22d9c13de21a74461
        with:
          check_filenames: true
          check_hidden: true
          skip: ./target,./cbits/cbits,./.jj,*.lock
          ignore_words_list: crate,tread
